### ISSUE TITLE
amun-inspection inspection runs are failing

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#104]
**Describe the bug**
After the successfully build of the specification the inspection runs fails with following error:
```
+ results=/mnt/results/
+ mkdir -p /mnt/results/
+ pod_json=/tmp/amun-inspection-pod.json
++ kubectl get pods --selector workflows.argoproj.io/workflow=inspection-test-1e6b0b03,inspection=job --output json
++ jq -r '.items[].metadata.name'
+ pod_names=inspection-test-1e6b0b03-3744296976
+ cnt=0
+ exit_code=0
+ IFS=''
+ for name in $pod_names
+ let cnt+=1
+ mkdir -p /mnt/results//1
+ kubectl get pod inspection-test-1e6b0b03-3744296976 -o json
++ cat /tmp/amun-inspection-pod.json
++ jq '.status.containerStatuses[] |       select(.name == "main") | .state.terminated.exitCode'
+ container_exit_code=null
+ let exit_code+=null
/argo/staging/script: line 24: null: unbound variable
```

**To Reproduce**
1. Go tohttp://amun-api-thoth-test-core.apps.ocp.prod.psi.redhat.com/api/v1/ui/#/Inspection/post_inspection
2. Click on 'try-out'
3. See an error in the workflow

**Expected behavior**
successful execution of amun-inspection runs.

**Additional context**
Issue is occurring due to init error the inspection run.

**Comment by harshad16** [comment]
The issue seemed to be due the old image of amun-hwinfo image. Using the pipeline updated the image, the issue still persisted.

**Comment by harshad16** [comment]
The amun-inspect-hwinfo is failing on the initiation of container with following issue:
```
Traceback (most recent call last):
--
  | File "app.py", line 856, in <module>
  | platform = platforminfo()
  | File "app.py", line 826, in platforminfo
  | "architecture": platform.architecture(),
  | NameError: name 'platform' is not defined
```

**Comment by harshad16** [comment]
This is related to: https://github.com/thoth-station/amun-hwinfo/issues/25
Solved by: https://github.com/thoth-station/amun-hwinfo/pull/26
