### ISSUE TITLE
Service Unavailable for url: http://qeb-hwt-webhook-receiver-thoth-frontend-prod.apps.zero.massopen.cloud.com/

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1061]
**Describe the bug**
Service Unavailable for url: http://qeb-hwt-webhook-receiver-thoth-frontend-prod.apps.zero.massopen.cloud.com/

**To Reproduce**
1. Start qeb-hwt

**Expected behavior**
qeb-hwt workflow runs successfully

**Screenshots**
```
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1615800007.5872426, "asctime": "2021-03-15 09:20:07,587", "msecs": 587.242603302002, "relative_created": 6486.169099807739, "process": 1, "message": "Logging to a Sentry instance is turned off"}
Traceback (most recent call last):
  File "qeb_thamos_advise.py", line 153, in <module>
    qeb_hwt_thamos_advise()
  File "qeb_thamos_advise.py", line 100, in qeb_hwt_thamos_advise
    trigger_finished_webhook(exception_message=exception_message, has_error=True, error_type="MissingThothYamlFile")
  File "/opt/app-root/src/thoth/workflow_helpers/trigger_finished_webhook.py", line 117, in trigger_finished_webhook
    response.raise_for_status()
  File "/opt/app-root/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://qeb-hwt-webhook-receiver-thoth-frontend-prod.apps.zero.massopen.cloud.com/

**Additional context**
Add any other context about the problem here.

**Comment by goern** [comment]
https://github.com/thoth-station/qeb-hwt/issues/143 might be related

**Comment by goern** [comment]
fixed by https://github.com/thoth-station/thoth-application/commit/3200de4b7696669448d4e2afc3680dc4e877915c

**Comment by goern** [comment]
it is deployed to /label deployment_name/zero-prod please check and close the issue

**Comment by goern** [comment]
I founds two more... fixed in https://github.com/thoth-station/thoth-application/commit/334b3f5306e7ebecd58e00e3dea2ef6323f0e423

**Comment by harshad16** [comment]
Thanks for fixing this.
Closing the issue.
