### ISSUE TITLE
SSL verify errors during integration tests

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1581]
**Describe the bug**
```
Feature: Aggregating Build Logs # features/aggregate_build_logs.feature:1
  @seizes_amun_inspection_namespace
  Scenario: Browsing logs of container images builds during Amun inspection jobs  # features/aggregate_build_logs.feature:4
    Given amun service is accessible using HTTPS                                  # features/steps/amun_api.py:42
      Traceback (most recent call last):
        File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
          httplib_response = self._make_request(
        File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
          self._validate_conn(conn)
        File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
          conn.connect()
        File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connection.py", line 411, in connect
          self.sock = ssl_wrap_socket(
        File "/opt/app-root/lib64/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
          ssl_sock = _ssl_wrap_socket_impl(
        File "/opt/app-root/lib64/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
          return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
        File "/usr/lib64/python3.8/ssl.py", line 500, in wrap_socket
          return self.sslsocket_class._create(
        File "/usr/lib64/python3.8/ssl.py", line 1040, in _create
          self.do_handshake()
        File "/usr/lib64/python3.8/ssl.py", line 1309, in do_handshake
          self._sslobj.do_handshake()
      ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)
```

**To Reproduce**
1. Go to any inegration-tests job log, https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/logs/integration-tests-moc/1401166689982222336

**Expected behavior**
SSL cert is valid.

**Screenshots**
n/a

**Additional context**
n/a

/assign @harshad16

**Comment by harshad16** [comment]
This would have been fixed by : https://github.com/thoth-station/thoth-application/pull/1607

**Comment by fridex** [comment]
We had also an issue in thamos - thamos was not correctly respecting `tls_verify` configuration option from the config file. Now it correctly handles TLS verification - of course, not recommended to turn it of though - https://github.com/thoth-station/thamos/pull/860

**Comment by fridex** [comment]
Closing as the issue was addressed with renewed certificates (thanks @harshad16).

/close
