### ISSUE TITLE
ERROR: pgbouncer cannot connect to the server [ocp4:thoth-test-core]

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#1605]
**Describe the bug**
Seems that the database is not running in `thoth-test-core` namespace on `ocp4`.

When creating a job out of `mi-scheduler` cronjob, this error can be seen from its output -`mi-schedule` is calling `storages` to retrieve the list of kebechet repositories, but it fails to do so. See LOG for more.

**To Reproduce**
  

1. Login to ocp4
2. `oc project thoth-test-core`
3. `oc create job --from=cronjob/mi-scheduler-kebechet mi-test`
4. wait a few seconds
5. `oc logs -f mi-test-....`

**LOG**
```
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1623067928.5854177, "asctime": "2021-06-07 12:12:08,585", "msecs": 585.4177474975586, "relative_created": 8205.80244064331, "process": 1, "message": "Logging to a Sentry instance is turned off"}
{"name": "thoth.mi-scheduler", "levelname": "INFO", "module": "app", "lineno": 148, "funcname": "<module>", "created": 1623067928.585843, "asctime": "2021-06-07 12:12:08,585", "msecs": 585.8430862426758, "relative_created": 8206.227779388428, "process": 1, "message": "mi-scheduler for scheduling mi workflows v1.4.0"}
{"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 163, "funcname": "__init__", "created": 1623067928.6876235, "asctime": "2021-06-07 12:12:08,687", "msecs": 687.6235008239746, "relative_created": 8308.008193969727, "process": 1, "message": "TLS verification when communicating with k8s/okd master is disabled"}
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/app-root/lib64/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: ERROR:  pgbouncer cannot connect to server


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 149, in <module>
    main()
  File "app.py", line 138, in main
    graph.connect()
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 299, in connect
    if not database_exists(self._engine.url):
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres_utils.py", line 84, in database_exists
    return bool(get_scalar_result(engine, text))
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres_utils.py", line 72, in get_scalar_result
    result_proxy = engine.execute(sql)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2234, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/app-root/lib64/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) ERROR:  pgbouncer cannot connect to server

(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by harshad16** [comment]
The application was stuck due to network issue.
Restarting the app has fixed the issue.
Please verify it. closing the issue, please feel free to reopen.

**Comment by xtuchyna** [comment]
Everything seems to be okay, thanks!
