### ISSUE TITLE
Kebechet prod hit api rate limit.

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1651]
**Describe the bug**
Kebechet prod hit api rate limit.

**To Reproduce**
1. Schedule Kebechet for a release for example

**Expected behavior**
No error produced.

**Screenshots**
```
2021-06-10 11:41:02,979   1 WARNING  ogr.services.github.service:104: Ignored keyword arguments: {'github_private_key_path': '/home/user/github/github-privatekey'}
2021-06-10 11:41:03,073   1 CRITICAL root:105: Traceback (most recent call last):
  File "kebechet-cli", line 137, in <module>
    cli()
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "kebechet-cli", line 133, in cli_run_webhook
    run_webhook(payload=payload)
  File "/home/user/kebechet/kebechet_runners.py", line 67, in run_webhook
    run_url(url, service_type, parsed_payload)
  File "/home/user/kebechet/kebechet_runners.py", line 87, in run_url
    run(
  File "/home/user/kebechet/kebechet_runners.py", line 133, in run
    with download_kebechet_config(ogr_service, namespace, project) as f:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/kebechet/utils.py", line 114, in download_kebechet_config
    branch = ogr_project.default_branch
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/project.py", line 175, in default_branch
    return self.github_repo.default_branch
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/ogr/services/github/project.py", line 94, in github_repo
    self._github_repo = self.github_instance.get_repo(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for 192.12.185.131. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Additional context**
See: https://github.com/thoth-station/kebechet/issues/747

**Comment by goern** [comment]
Shall we put in a rate limit check and report it as a metric? seeAlso https://docs.github.com/en/rest/reference/rate-limit

**Comment by KPostOffice** [comment]
Yeah, this is a good idea. We should be able to plot this against Kebechet runs to see how many API requests each workflow is generating.

**Comment by goern** [comment]
> Yeah, this is a good idea. We should be able to plot this against Kebechet runs to see how many API requests each workflow is generating.

@KPostOffice could you please create a feature issue out of this?
