### ISSUE TITLE
qeb-hwt workflow failing due to ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1654]
**Describe the bug**
qeb-hwt workflow failing due to ModuleNotFoundError: No module named 'typing_extensions'

**To Reproduce**
1. Schedule qeb-hwt

**Expected behavior**
workflow ends successfully

**Screenshots**
```
Traceback (most recent call last):
  File "qeb_thamos_advise.py", line 26, in <module>
    from thoth.python import Project
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/__init__.py", line 20, in <module>
    from .aiosource import AIOSource
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/aiosource.py", line 26, in <module>
    import aiohttp
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/helpers.py", line 48, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

**Additional context**

**Comment by pacospace** [comment]
Deprecated
