### ISSUE TITLE
Stage ingestion halted due to undefined table in graph-sync

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1975]
**Describe the bug**

```python
2021-09-20 07:59:43,879   1 CRITICAL root:105: Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "import_package" does not exist
LINE 2: FROM import_package
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 252, in <module>
    cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "app.py", line 226, in cli
    _do_sync(
  File "app.py", line 125, in _do_sync
    stats = sync_documents(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/sync.py", line 574, in sync_documents
    stats_change = handler(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/sync.py", line 131, in sync_solver_documents
    graph.sync_solver_result(document, force=force)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 5459, in sync_solver_result
    import_package, _ = ImportPackage.get_or_create(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/models_base.py", line 44, in get_or_create
    instance = session.query(cls).filter_by(**kwargs).first()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "import_package" does not exist
LINE 2: FROM import_package
             ^

[SQL: SELECT import_package.id AS import_package_id, import_package.import_package_name AS import_package_import_package_name
FROM import_package
WHERE import_package.import_package_name = %(import_package_name_1)s
 LIMIT %(param_1)s]
[parameters: {'import_package_name_1': 'lib.ansible', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**To Reproduce**
1. Go to the stage environment
2. Check ingestion
3. Check graph-sync component logs
4. See the error

**Expected behavior**

Graph sync should succeed.

**Additional context**

It looks like the database schema is old in the stage environment - '65ae36e5c38a'.

**Comment by fridex** [comment]
Was checking other components - user-api and management-api. Do they have the schema in sync?

**Comment by pacospace** [comment]
> Was checking other components - user-api and management-api. Do they have the schema in sync?

You can check this from: https://grafana.datahub.redhat.com/dashboard/db/thoth-service-metrics?refresh=30s&orgId=1

And it seems they have same:
![Screenshot from 2021-09-20 13-34-00](https://user-images.githubusercontent.com/27498679/133995863-7ecdba59-0d94-4c25-b9e3-4f68f51546bf.png)

![Screenshot from 2021-09-20 13-37-25](https://user-images.githubusercontent.com/27498679/133996112-dd32d097-796c-448a-a383-a051b7abb532.png)

**Comment by fridex** [comment]
@pacospace Do we have an alert for this case?

**Comment by pacospace** [comment]
> @pacospace Do we have an alert for this case?

Yes in stage we receive them by email (I see they are triggered because metrics-exporter is not deployed with latest storages), while in prod will open github issues.

**Comment by fridex** [comment]
ACK, thanks for the info.

**Comment by pacospace** [comment]
> ACK, thanks for the info.

redeployed metrics-exporter, now alarms will be triggered for missing components with schema not updated.
