### ISSUE TITLE
SLO repoter cannot access https://thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud 

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2142]
**Describe the bug**
SLO repoter cannot access https://thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud 
**To Reproduce**
1. Schedule cronjob in stage

**Expected behavior**
SLO reporter can connect to Prometheus/Thanos and get metrics.

**Screenshots**
```
INFO:thoth.slo_reporter:Interval: 2021-11-09 - 2021-11-10
Traceback (most recent call last):
  File "app.py", line 469, in <module>
    main()
  File "app.py", line 459, in main
    run_slo_reporter(
  File "app.py", line 381, in run_slo_reporter
    raise Exception(f"Thanos endpoint {configuration.thanos_url} is not available! SLO-reporter cannot run.")
Exception: Thanos endpoint https://thanos-querier-openshift-monitoring.apps.smaug.na.operate-first.cloud is not available! SLO-reporter cannot run.
```

**Additional context**

**Comment by pacospace** [comment]
This was actually solved by @harshad16! we can close this :)

**Comment by pacospace** [comment]
PR that solved it: https://github.com/thoth-station/thoth-application/pull/2177
