### ISSUE TITLE
Pre-commit fails on the `black` test

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#2498]
**Describe the bug**
Related PR https://github.com/thoth-station/mi-scheduler/pull/217

PR cannot pass `pre-commit` test because of the failing black test, the reason is invalid import in the `click` module

**LOGS**
```
 [INFO] Initializing environment for https://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://gitlab.com/PyCQA/flake8.
[INFO] Initializing environment for https://gitlab.com/PyCQA/flake8:pep8-naming.
[INFO] Installing environment for https://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitlab.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Fix End of Files.........................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
Check for byte-order marker..............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
  File "/opt/app-root/src/.cache/pre-commit/repod0a21ho8/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/opt/app-root/src/.cache/pre-commit/repod0a21ho8/py_env-python3/lib/python3.8/site-packages/black.py", line 4134, in patched_main
    patch_click()
  File "/opt/app-root/src/.cache/pre-commit/repod0a21ho8/py_env-python3/lib/python3.8/site-packages/black.py", line 4123, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/opt/app-root/src/.cache/pre-commit/repod0a21ho8/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
flake8...................................................................Passed 
```

**Comment by xtuchyna** [comment]
After `autoupdate` the pre-commit hook output is:
```
 [INFO] Initializing environment for https://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[ERROR] The hook `mypy` requires pre-commit version 2.9.2 but version 2.7.1 is installed.  Perhaps run `pip install --upgrade pre-commit`. 
```

**Comment by xtuchyna** [comment]
The issue still prevails after fixing `pre-commit==2.15.0` , I cannot reproduce it locally

```
(mi-scheduler) [xtuchyna@localhost mi-scheduler (update/dependencies %)]$ pip show pre-commit
Name: pre-commit
Version: 2.15.0
Summary: A framework for managing and maintaining multi-language pre-commit hooks.
Home-page: https://github.com/pre-commit/pre-commit
Author: Anthony Sottile
Author-email: asottile@umich.edu
License: MIT
Location: /home/xtuchyna/.local/share/virtualenvs/mi-scheduler-mGsCfD-C/lib/python3.8/site-packages
Requires: cfgv, identify, nodeenv, pyyaml, toml, virtualenv
Required-by: 
(mi-scheduler) [xtuchyna@localhost mi-scheduler (update/dependencies %)]$  pre-commit run mypy --all-files
mypy.....................................................................Passed
```

**Comment by xtuchyna** [comment]
Temporarily ignoring both `mypy` and `black` solved the issue, leaving this open until pernament solution is found

**Comment by xtuchyna** [comment]
**UPDATE:**
The issue was with both `mypy` and `black` hooks active in pre-commit configuration file.

The error in job always resulted in:
```
The hook `mypy|black` requires pre-commit version 2.9.2 but version 2.7.1 is installed.  Perhaps run `pip install --upgrade pre-commit`. 
```

After ignoring these tests (commenting them out), `pre-commit` checks passed.

pre-commit mypy and black configuration:
```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        exclude: '^(docs|tasks|tests)|setup\.py'
        args: [--ignore-missing-imports]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
```
https://github.com/thoth-station/mi-scheduler/blob/master/.pre-commit-config.yaml

**Comment by harshad16** [comment]
as the update pre-commit is required, we would have to update pre-commit in .prow.yaml
please update the version `v0.14.3` at https://github.com/thoth-station/mi-scheduler/blob/2a37d68b4f215b044ca8799329fc75625c5d4e83/.prow.yaml#L9
