### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known',

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#392]
**Describe the bug**
I spotted this error in some qeb-hwt workflow, not sure why it is random.

**To Reproduce**
1. Open PR in any project with Qeb-Hwt
2. Have a look at workflows in thoth-backend-stage

**Expected behavior**
Check run is sent back to PR.

**Screenshots**
inputs
```

Name:                qeb-hwt-c188ec58
Namespace:           thoth-backend-stage
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Wed Sep 09 11:12:22 +0200 (41 minutes ago)
Started:             Wed Sep 09 11:12:33 +0200 (41 minutes ago)
Finished:            Wed Sep 09 11:12:52 +0200 (41 minutes ago)
Duration:            19 seconds
ResourcesDuration:   26s*cpu,36s*memory
Parameters:          
  GITHUB_EVENT_TYPE: thoth_thamos_advise
  GITHUB_CHECK_RUN_ID: 1090296355
  GITHUB_INSTALLATION_ID: 6181026
  GITHUB_HEAD_REPO_URL: https://github.com/harshad16/thoth-application
  GITHUB_BASE_REPO_URL: https://api.github.com/repos/thoth-station/thoth-application
  ORIGIN:            https://github.com/harshad16/thoth-application
  REVISION:          2269c5487da913ae58a6f5ecda8149b6de52de5e
  THOTH_HOST:        khemenu.thoth-station.ninja

STEP                      TEMPLATE                                 PODNAME                     DURATION  MESSAGE
 ✖ qeb-hwt-c188ec58       qeb-hwt                                                                                                 
 └-✖ qeb-hwt-integration  qeb-hwt-integration/qeb-hwt-integration  qeb-hwt-c188ec58-497678642  19s       failed with exit code 1  

```

logs
```
qeb-hwt-c188ec58-497678642: 2020-09-09 09:12:44,589   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
qeb-hwt-c188ec58-497678642: 2020-09-09 09:12:44,589   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
qeb-hwt-c188ec58-497678642: 2020-09-09 09:12:44,593   1 INFO     trigger_finished_webhook:112: Headers:
qeb-hwt-c188ec58-497678642: 
qeb-hwt-c188ec58-497678642: 2020-09-09 09:12:44,593   1 INFO     trigger_finished_webhook:113: Data:
qeb-hwt-c188ec58-497678642: 
qeb-hwt-c188ec58-497678642:     (self._dns_host, self.port), self.timeout, **extra_kw
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
qeb-hwt-c188ec58-497678642: 2020-09-09 09:12:49,732   1 CRITICAL root:102: Traceback (most recent call last):
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
qeb-hwt-c188ec58-497678642:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
qeb-hwt-c188ec58-497678642:   File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
qeb-hwt-c188ec58-497678642:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
qeb-hwt-c188ec58-497678642: socket.gaierror: [Errno -2] Name or service not known
qeb-hwt-c188ec58-497678642: 
qeb-hwt-c188ec58-497678642: During handling of the above exception, another exception occurred:
qeb-hwt-c188ec58-497678642: 
qeb-hwt-c188ec58-497678642: Traceback (most recent call last):
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
qeb-hwt-c188ec58-497678642:     chunked=chunked,
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
qeb-hwt-c188ec58-497678642:     conn.request(method, url, **httplib_request_kw)
qeb-hwt-c188ec58-497678642:   File "/usr/lib64/python3.6/http/client.py", line 1254, in request
qeb-hwt-c188ec58-497678642:     self._send_request(method, url, body, headers, encode_chunked)
qeb-hwt-c188ec58-497678642:   File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
qeb-hwt-c188ec58-497678642:     self.endheaders(body, encode_chunked=encode_chunked)
qeb-hwt-c188ec58-497678642:   File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
qeb-hwt-c188ec58-497678642:     self._send_output(message_body, encode_chunked=encode_chunked)
qeb-hwt-c188ec58-497678642:   File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
qeb-hwt-c188ec58-497678642:     self.send(msg)
qeb-hwt-c188ec58-497678642:   File "/usr/lib64/python3.6/http/client.py", line 974, in send
qeb-hwt-c188ec58-497678642:     self.connect()
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
qeb-hwt-c188ec58-497678642:     conn = self._new_conn()
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
qeb-hwt-c188ec58-497678642:     self, "Failed to establish a new connection: %s" % e
qeb-hwt-c188ec58-497678642: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3b979f0080>: Failed to establish a new connection: [Errno -2] Name or service not known
qeb-hwt-c188ec58-497678642: 
qeb-hwt-c188ec58-497678642: During handling of the above exception, another exception occurred:
qeb-hwt-c188ec58-497678642: 
qeb-hwt-c188ec58-497678642: Traceback (most recent call last):
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
qeb-hwt-c188ec58-497678642:     timeout=timeout
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
qeb-hwt-c188ec58-497678642:     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
qeb-hwt-c188ec58-497678642:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
qeb-hwt-c188ec58-497678642: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='qeb-hwt-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b979f0080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
qeb-hwt-c188ec58-497678642: 
qeb-hwt-c188ec58-497678642: During handling of the above exception, another exception occurred:
qeb-hwt-c188ec58-497678642: 
qeb-hwt-c188ec58-497678642: Traceback (most recent call last):
qeb-hwt-c188ec58-497678642:   File "qeb_thamos_advise.py", line 133, in <module>
qeb-hwt-c188ec58-497678642:     qeb_hwt_thamos_advise()
qeb-hwt-c188ec58-497678642:   File "qeb_thamos_advise.py", line 96, in qeb_hwt_thamos_advise
qeb-hwt-c188ec58-497678642:     trigger_finished_webhook(exception_message=exception_message, has_error=True, error_type="MissingThothYamlFile")
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/src/thoth/workflow_helpers/trigger_finished_webhook.py", line 115, in trigger_finished_webhook
qeb-hwt-c188ec58-497678642:     response = requests.post(Configuration._WEBHOOK_CALLBACK_URL, data=json.dumps(data), headers=headers)
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/requests/api.py", line 119, in post
qeb-hwt-c188ec58-497678642:     return request('post', url, data=data, json=json, **kwargs)
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/requests/api.py", line 61, in request
qeb-hwt-c188ec58-497678642:     return session.request(method=method, url=url, **kwargs)
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
qeb-hwt-c188ec58-497678642:     resp = self.send(prep, **send_kwargs)
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
qeb-hwt-c188ec58-497678642:     r = adapter.send(request, **kwargs)
qeb-hwt-c188ec58-497678642:   File "/opt/app-root/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
qeb-hwt-c188ec58-497678642:     raise ConnectionError(e, request=request)
qeb-hwt-c188ec58-497678642: requests.exceptions.ConnectionError: HTTPConnectionPool(host='qeb-hwt-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b979f0080>: Failed to establish a new connection: [Errno -2] Name or service not known',))

```

**Additional context**

**Comment by fridex** [comment]
This looks like an issue related to the networking hiccups we observed in the cluster. Feel free to reopen if the issue persists.
