### ISSUE TITLE
SI workflow is not able to sync in Thoth Database

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#442]
**Describe the bug**
SI workflow is not able to sync in Thoth Database

**To Reproduce**
1. Schedule an SI workflow

**Expected behavior**
SI workflow syncs correctly

**Screenshots**
```
security-indicator-77a01786-1801069231: 2020-09-16 13:59:56,293   1 INFO     thoth.common:325: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'ocp-test' and integrations ['SqlalchemyIntegration']
security-indicator-77a01786-1801069231: 2020-09-16 13:59:56,299   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-77a01786-1801069231: 2020-09-16 13:59:56,300   1 INFO     thoth.graph_sync_job:236: graph-sync-job v0.7.3+thoth_storage.0.25.8+thoth_common.0.18.3 starting...
security-indicator-77a01786-1801069231: 2020-09-16 13:59:56,374   1 DEBUG    thoth.graph_sync_job:209: Debug mode is on
security-indicator-77a01786-1801069231: 2020-09-16 13:59:56,680   1 INFO     alembic.runtime.migration:155: Context impl PostgresqlImpl.
security-indicator-77a01786-1801069231: 2020-09-16 13:59:56,680   1 INFO     alembic.runtime.migration:162: Will assume transactional DDL.
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
security-indicator-77a01786-1801069231:   File "app.py", line 237, in <module>
security-indicator-77a01786-1801069231:     cli()
security-indicator-77a01786-1801069231: 
security-indicator-77a01786-1801069231:     return self.main(*args, **kwargs)
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
security-indicator-77a01786-1801069231:     rv = self.invoke(ctx)
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
security-indicator-77a01786-1801069231:     return ctx.invoke(self.callback, **ctx.params)
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
security-indicator-77a01786-1801069231:     return callback(*args, **kwargs)
security-indicator-77a01786-1801069231:   File "app.py", line 217, in cli
security-indicator-77a01786-1801069231:     is_local=local_file,
security-indicator-77a01786-1801069231:   File "app.py", line 117, in _do_sync
security-indicator-77a01786-1801069231: 2020-09-16 13:59:58,093   1 CRITICAL root:102: Traceback (most recent call last):
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 688, in sync_documents
security-indicator-77a01786-1801069231:     to_sync_document_id, force=force, graceful=graceful, graph=graph, is_local=is_local
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 608, in sync_security_indicators_documents
security-indicator-77a01786-1801069231:     graph.sync_security_indicator_aggregated_result(aggregated_document)
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 5107, in sync_security_indicator_aggregated_result
security-indicator-77a01786-1801069231:     python_package_version=python_package_version_id,
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 44, in get_or_create
security-indicator-77a01786-1801069231:     instance = session.query(cls).filter_by(**kwargs).first()
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1907, in filter_by
security-indicator-77a01786-1801069231:     for key, value in kwargs.items()
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1907, in <listcomp>
security-indicator-77a01786-1801069231:     for key, value in kwargs.items()
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/operators.py", line 365, in __eq__
security-indicator-77a01786-1801069231:     return self.operate(eq, other)
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 219, in operate
security-indicator-77a01786-1801069231:     return op(self.comparator, *other, **kwargs)
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1268, in __eq__
security-indicator-77a01786-1801069231:     other, adapt_source=self.adapter
security-indicator-77a01786-1801069231:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py", line 1653, in _optimized_compare
security-indicator-77a01786-1801069231:     "use %s.has(**criteria)." % self
security-indicator-77a01786-1801069231: sqlalchemy.exc.ArgumentError: Mapped instance expected for relationship comparison to object.   Classes, queries and other SQL elements are not accepted in this context; for comparison with a subquery, use SIAggregated.python_package_version.has(**criteria).
security-indicator-77a01786-1801069231:     is_local=is_local,
security-indicator-77a01786-1801069231: Press Ctrl-C to quit
security-indicator-77a01786-1801069231: Sentry is attempting to send 1 pending error messages
security-indicator-77a01786-1801069231: Waiting up to 2 seconds
```

**Additional context**
![Screenshot from 2020-09-16 16-01-25](https://user-images.githubusercontent.com/27498679/93348569-ad70e180-f836-11ea-803e-b2ce86112753.png)

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/adviser/issues/1178
