### ISSUE TITLE
Cannot obtain container logs from user-api

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#459]
**Describe the bug**
```
Kubernetes master response for pod log (%d): %r 403 {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"adviser-d65f22b6-4264199469\" is forbidden: User \"system:serviceaccount:thoth-frontend-stage:user-api\" cannot get resource \"pods/log\" in API group \"\" in the namespace \"thoth-backend-stage\"","reason":"Forbidden","details":{"name":"adviser-d65f22b6-4264199469","kind":"pods"},"code":403}

Error response when obtaining pod logs: %r {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'pods "adviser-d65f22b6-4264199469" is forbidden: User "system:serviceaccount:thoth-frontend-stage:user-api" cannot get resource "pods/log" in API group "" in the namespace "thoth-backend-stage"', 'reason': 'Forbidden', 'details': {'name': 'adviser-d65f22b6-4264199469', 'kind': 'pods'}, 'code': 403}
Traceback (most recent call last):
  File "a.py", line 61, in get_pod_log
    response.raise_for_status()
  File "/opt/app-root/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://172.30.0.1:443/api/v1/namespaces/thoth-backend-stage/pods/adviser-d65f22b6-4264199469/log?container=main
```

**To Reproduce**
1. Issue `thamos advise --nowiat`
2. Issue `thamos log`
3. See error

**Expected behavior**

`thamos log` should succeed

**Comment by fridex** [comment]
I still see this one in OCP/stage deployment:

```
{
    'name': 'thoth.common.openshift', 
    'levelname': 'ERROR', 
    'module': 'openshift', 
    'lineno': 373, 
    'funcname': 'get_pod_log', 
    'created': 1601036403.7262814, 
    'asctime': '2020-09-25 12:20:03,726', 
    'msecs': 726.2814044952393, 
    'relative_created': 19775127.029180527, 
    'process': 27, 
    'message': 'Error response when obtaining pod logs: {\'kind\': \'Status\', \'apiVersion\': \'v1\', \'metadata\': {}, \'status\': \'Failure\', \'message\': \'pods "adviser-878c49af-1252873762" is forbidden: User "system:serviceaccount:thoth-frontend-stage:user-api" cannot get resource "pods/log" in API group "" in the namespace "thoth-backend-stage"\', \'reason\': \'Forbidden\', \'details\': {\'name\': \'adviser-878c49af-1252873762\', \'kind\': \'pods\'}, \'code\': 403}'
}
```

But I don't see this role being created in ocp/stage

CC @harshad16 PTAL
https://github.com/thoth-station/thoth-application/blob/bffb010d11853e5b6af40cd6d185bdfbbdfe71b0/user-api/base/role.yaml#L30-L38

**Comment by harshad16** [comment]
Thanks again, 
i will check on this.
and try to resolve as soon as possible

**Comment by fridex** [comment]
> Thanks again,
> i will check on this.
> and try to resolve as soon as possible

Thanks! It's not critical though. :+1:
