### ISSUE TITLE
Kafka fails in test while testing Qeb-hwt

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/thoth-application#561]
**Describe the bug**
Qebhwt fails on testing in thoth-test-core
**To Reproduce**
Go to user-api - 
Call /qeb-hwt with this body - 
```
{
  "github_base_repo_url": "https://api.github.com/repos/thoth-station/adviser",
  "github_check_run_id": 1241924102,
  "github_event_type": "thoth_thamos_advise",
  "github_head_repo_url": "https://github.com/fridex/adviser",
  "github_installation_id": 6181026,
  "origin": "https://github.com/fridex/adviser",
  "revision": "6c7bea7916959bd03c7cb067883c6edd674e8972"
}
```
**Additional context**
Log - 
```
FATA[0000] workflows.argoproj.io "qeb-hwt-fc7277be.send-messages" not found 
[sai@sai-pc workflow-helpers]$ argo logs qeb-hwt-fc7277be
qeb-hwt-fc7277be-3481824562: {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1602515221.100406, "asctime": "2020-10-12 15:07:01,100", "msecs": 100.40593147277832, "relative_created": 8310.014724731445, "process": 1, "message": "Logging to a Sentry instance is turned off"}
qeb-hwt-fc7277be-1666016770: [2020-10-12 15:09:11,340] [21] [WARNING] Logging to a Sentry instance is turned off 
qeb-hwt-fc7277be-1666016770: {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1602515351.3409853, "asctime": "2020-10-12 15:09:11,340", "msecs": 340.9852981567383, "relative_created": 3616.9655323028564, "process": 21, "message": "Logging to a Sentry instance is turned off"}
qeb-hwt-fc7277be-1666016770: [2020-10-12 15:09:11,428] [21] [WARNING] Unable to request metadata from "thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com:443": ConnectionError: Connection at thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com:443 closed 
qeb-hwt-fc7277be-1666016770: {"name": "aiokafka", "levelname": "WARNING", "module": "client", "lineno": 212, "funcname": "bootstrap", "created": 1602515351.4284875, "asctime": "2020-10-12 15:09:11,428", "msecs": 428.48753929138184, "relative_created": 3704.4677734375, "process": 21, "message": "Unable to request metadata from \"thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com:443\": ConnectionError: Connection at thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com:443 closed"}
qeb-hwt-fc7277be-1666016770:     self.loop.run_until_complete(self._starting_fut)
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
qeb-hwt-fc7277be-1666016770: Traceback (most recent call last):
qeb-hwt-fc7277be-1666016770:   File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
qeb-hwt-fc7277be-1666016770:     return future.result()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
qeb-hwt-fc7277be-1666016770:     await self._default_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
qeb-hwt-fc7277be-1666016770:     await self._actually_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
qeb-hwt-fc7277be-1666016770:     await child.maybe_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
qeb-hwt-fc7277be-1666016770:     await self.start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
qeb-hwt-fc7277be-1666016770:     await self._default_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
qeb-hwt-fc7277be-1666016770:     await self._actually_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
qeb-hwt-fc7277be-1666016770:     await self.on_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1073, in on_start
qeb-hwt-fc7277be-1666016770:     await self._fut
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 598, in execute
qeb-hwt-fc7277be-1666016770: [2020-10-12 15:09:11,434] [21] [ERROR] [^Worker]: Error: ConnectionError("Unable to bootstrap from [('thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com', 443, <AddressFamily.AF_UNSPEC: 0>)]",) 
qeb-hwt-fc7277be-1666016770:     await self.run(*args, **kwargs)
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/src/cli.py", line 161, in messaging
qeb-hwt-fc7277be-1666016770:     await topic.topic.maybe_declare()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/utils/futures.py", line 55, in __call__
qeb-hwt-fc7277be-1666016770:     result = await self.fun(*self.args, **self.kwargs)
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/topics.py", line 455, in maybe_declare
qeb-hwt-fc7277be-1666016770:     await self.declare()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/topics.py", line 466, in declare
qeb-hwt-fc7277be-1666016770:     producer = await self._get_producer()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/topics.py", line 379, in _get_producer
qeb-hwt-fc7277be-1666016770:     return await self.app.maybe_start_producer()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/utils/futures.py", line 55, in __call__
qeb-hwt-fc7277be-1666016770:     result = await self.fun(*self.args, **self.kwargs)
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/app/base.py", line 1449, in maybe_start_producer
qeb-hwt-fc7277be-1666016770:     await producer.maybe_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
qeb-hwt-fc7277be-1666016770: kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com', 443, <AddressFamily.AF_UNSPEC: 0>)]
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
qeb-hwt-fc7277be-1666016770:     await self._default_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
qeb-hwt-fc7277be-1666016770:     await self._actually_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
qeb-hwt-fc7277be-1666016770:     await self.on_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 1021, in on_start
qeb-hwt-fc7277be-1666016770:     await producer.start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 178, in start
qeb-hwt-fc7277be-1666016770:     await self.client.bootstrap()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/aiokafka/client.py", line 231, in bootstrap
qeb-hwt-fc7277be-1666016770:     'Unable to bootstrap from {}'.format(self.hosts))
qeb-hwt-fc7277be-1666016770:     await self.start()
qeb-hwt-fc7277be-1666016770: {"name": "mode.worker", "levelname": "ERROR", "module": "logging", "lineno": 267, "funcname": "log", "created": 1602515351.434733, "asctime": "2020-10-12 15:09:11,434", "msecs": 434.73291397094727, "relative_created": 3710.7131481170654, "process": 21, "message": "[^Worker]: Error: ConnectionError(\"Unable to bootstrap from [('thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com', 443, <AddressFamily.AF_UNSPEC: 0>)]\",)\nTraceback (most recent call last):\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/worker.py\", line 273, in execute_from_commandline\n    self.loop.run_until_complete(self._starting_fut)\n  File \"/usr/lib64/python3.6/asyncio/base_events.py\", line 484, in run_until_complete\n    return future.result()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 736, in start\n    await self._default_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 743, in _default_start\n    await self._actually_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 767, in _actually_start\n    await child.maybe_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 795, in maybe_start\n    await self.start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 736, in start\n    await self._default_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 743, in _default_start\n    await self._actually_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 760, in _actually_start\n    await self.on_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 1073, in on_start\n    await self._fut\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py\", line 598, in execute\n    await self.run(*args, **kwargs)\n  File \"/opt/app-root/src/cli.py\", line 161, in messaging\n    await topic.topic.maybe_declare()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/utils/futures.py\", line 55, in __call__\n    result = await self.fun(*self.args, **self.kwargs)\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/topics.py\", line 455, in maybe_declare\n    await self.declare()\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/topics.py\", line 466, in declare\n    producer = await self._get_producer()\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/topics.py\", line 379, in _get_producer\n    return await self.app.maybe_start_producer()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/utils/futures.py\", line 55, in __call__\n    result = await self.fun(*self.args, **self.kwargs)\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/app/base.py\", line 1449, in maybe_start_producer\n    await producer.maybe_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 795, in maybe_start\n    await self.start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 736, in start\n    await self._default_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 743, in _default_start\n    await self._actually_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 760, in _actually_start\n    await self.on_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py\", line 1021, in on_start\n    await producer.start()\n  File \"/opt/app-root/lib/python3.6/site-packages/aiokafka/producer/producer.py\", line 178, in start\n    await self.client.bootstrap()\n  File \"/opt/app-root/lib/python3.6/site-packages/aiokafka/client.py\", line 231, in bootstrap\n    'Unable to bootstrap from {}'.format(self.hosts))\nkafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com', 443, <AddressFamily.AF_UNSPEC: 0>)]"}
qeb-hwt-fc7277be-1666016770: [2020-10-12 15:09:11,439] [21] [ERROR] [^Worker]: Error while stopping child <messaging: stopping >: ConnectionError("Unable to bootstrap from [('thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com', 443, <AddressFamily.AF_UNSPEC: 0>)]",) 
qeb-hwt-fc7277be-1666016770: Traceback (most recent call last):
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 863, in _default_stop_children
qeb-hwt-fc7277be-1666016770:     await asyncio.shield(child.stop())
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 839, in stop
qeb-hwt-fc7277be-1666016770:     await self.on_stop()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1084, in on_stop
qeb-hwt-fc7277be-1666016770:     fut.result()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
qeb-hwt-fc7277be-1666016770:     self.loop.run_until_complete(self._starting_fut)
qeb-hwt-fc7277be-1666016770:   File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
qeb-hwt-fc7277be-1666016770:     return future.result()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
qeb-hwt-fc7277be-1666016770:     await self._default_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
qeb-hwt-fc7277be-1666016770:     await self._actually_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
qeb-hwt-fc7277be-1666016770:     await child.maybe_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
qeb-hwt-fc7277be-1666016770:     await self.start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
qeb-hwt-fc7277be-1666016770:     await self._default_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
qeb-hwt-fc7277be-1666016770:     await self._actually_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
qeb-hwt-fc7277be-1666016770:     await self.on_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1073, in on_start
qeb-hwt-fc7277be-1666016770:     await self._fut
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 598, in execute
qeb-hwt-fc7277be-1666016770:     await self.run(*args, **kwargs)
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/src/cli.py", line 161, in messaging
qeb-hwt-fc7277be-1666016770: kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com', 443, <AddressFamily.AF_UNSPEC: 0>)]
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/utils/futures.py", line 55, in __call__
qeb-hwt-fc7277be-1666016770:     result = await self.fun(*self.args, **self.kwargs)
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/topics.py", line 455, in maybe_declare
qeb-hwt-fc7277be-1666016770:     await self.declare()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/topics.py", line 466, in declare
qeb-hwt-fc7277be-1666016770:     producer = await self._get_producer()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/topics.py", line 379, in _get_producer
qeb-hwt-fc7277be-1666016770:     return await self.app.maybe_start_producer()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/utils/futures.py", line 55, in __call__
qeb-hwt-fc7277be-1666016770:     result = await self.fun(*self.args, **self.kwargs)
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/app/base.py", line 1449, in maybe_start_producer
qeb-hwt-fc7277be-1666016770:     await producer.maybe_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
qeb-hwt-fc7277be-1666016770:     await self.start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
qeb-hwt-fc7277be-1666016770:     await self._default_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
qeb-hwt-fc7277be-1666016770:     await self._actually_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
qeb-hwt-fc7277be-1666016770:     await self.on_start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 1021, in on_start
qeb-hwt-fc7277be-1666016770:     await producer.start()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 178, in start
qeb-hwt-fc7277be-1666016770:     await self.client.bootstrap()
qeb-hwt-fc7277be-1666016770:   File "/opt/app-root/lib/python3.6/site-packages/aiokafka/client.py", line 231, in bootstrap
qeb-hwt-fc7277be-1666016770:     'Unable to bootstrap from {}'.format(self.hosts))
qeb-hwt-fc7277be-1666016770:     await topic.topic.maybe_declare()
qeb-hwt-fc7277be-1666016770: {"name": "mode.worker", "levelname": "ERROR", "module": "logging", "lineno": 267, "funcname": "log", "created": 1602515351.439156, "asctime": "2020-10-12 15:09:11,439", "msecs": 439.15605545043945, "relative_created": 3715.1362895965576, "process": 21, "message": "[^Worker]: Error while stopping child <messaging: stopping >: ConnectionError(\"Unable to bootstrap from [('thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com', 443, <AddressFamily.AF_UNSPEC: 0>)]\",)\nTraceback (most recent call last):\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 863, in _default_stop_children\n    await asyncio.shield(child.stop())\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 839, in stop\n    await self.on_stop()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 1084, in on_stop\n    fut.result()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/worker.py\", line 273, in execute_from_commandline\n    self.loop.run_until_complete(self._starting_fut)\n  File \"/usr/lib64/python3.6/asyncio/base_events.py\", line 484, in run_until_complete\n    return future.result()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 736, in start\n    await self._default_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 743, in _default_start\n    await self._actually_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 767, in _actually_start\n    await child.maybe_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 795, in maybe_start\n    await self.start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 736, in start\n    await self._default_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 743, in _default_start\n    await self._actually_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 760, in _actually_start\n    await self.on_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 1073, in on_start\n    await self._fut\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py\", line 598, in execute\n    await self.run(*args, **kwargs)\n  File \"/opt/app-root/src/cli.py\", line 161, in messaging\n    await topic.topic.maybe_declare()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/utils/futures.py\", line 55, in __call__\n    result = await self.fun(*self.args, **self.kwargs)\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/topics.py\", line 455, in maybe_declare\n    await self.declare()\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/topics.py\", line 466, in declare\n    producer = await self._get_producer()\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/topics.py\", line 379, in _get_producer\n    return await self.app.maybe_start_producer()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/utils/futures.py\", line 55, in __call__\n    result = await self.fun(*self.args, **self.kwargs)\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/app/base.py\", line 1449, in maybe_start_producer\n    await producer.maybe_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 795, in maybe_start\n    await self.start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 736, in start\n    await self._default_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 743, in _default_start\n    await self._actually_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/mode/services.py\", line 760, in _actually_start\n    await self.on_start()\n  File \"/opt/app-root/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py\", line 1021, in on_start\n    await producer.start()\n  File \"/opt/app-root/lib/python3.6/site-packages/aiokafka/producer/producer.py\", line 178, in start\n    await self.client.bootstrap()\n  File \"/opt/app-root/lib/python3.6/site-packages/aiokafka/client.py\", line 231, in bootstrap\n    'Unable to bootstrap from {}'.format(self.hosts))\nkafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com', 443, <AddressFamily.AF_UNSPEC: 0>)]"}

```

**Comment by pacospace** [comment]
Qeb-Hwt can be successfully scheduled from user-api after all changes. If you see still errors please reopen it.
