### ISSUE TITLE
HTTPError: 503 Server Error: Service Unavailable for url: http://qeb-hwt-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com/

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#588]
**Describe the bug**
HTTPError: 503 Server Error: Service Unavailable for url: http://qeb-hwt-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com/

**To Reproduce**
1. Open PR in repo with Qeb-Hwt installed

**Expected behavior**
Qeb-Hwt workflow finished successfully

**Screenshots**
```
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.339196861Z {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1603717209.3386626, "asctime": "2020-10-26 13:00:09,338", "msecs": 338.66262435913086, "relative_created": 7593.754053115845, "process": 1, "message": "Logging to a Sentry instance is turned off"}
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.385041682Z Traceback (most recent call last):
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.385041682Z   File "qeb_thamos_advise.py", line 149, in <module>
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.385548867Z     qeb_hwt_thamos_advise()
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.385548867Z   File "qeb_thamos_advise.py", line 96, in qeb_hwt_thamos_advise
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.385749257Z     trigger_finished_webhook(exception_message=exception_message, has_error=True, error_type="MissingThothYamlFile")
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.385749257Z   File "/opt/app-root/src/thoth/workflow_helpers/trigger_finished_webhook.py", line 117, in trigger_finished_webhook
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.386148663Z     response.raise_for_status()
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.386148663Z   File "/opt/app-root/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.38657732Z     raise HTTPError(http_error_msg, response=self)
qeb-hwt-4d162857-2699826950: 2020-10-26T13:00:09.38657732Z requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://qeb-hwt-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com/
```

**Additional context**

**Comment by goern** [comment]
have we renamed the service to `http://sefkhet-abwy-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com/` ?

**Comment by harshad16** [comment]
> have we renamed the service to `http://sefkhet-abwy-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com/` ?

no we havent
