### ISSUE TITLE
KafkaException: KafkaError{code=_SSL,val=-181,str="Failed to query logical offset END: Local: SSL error"}

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#614]
```
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1604498660.6785111, "asctime": "2020-11-04 14:04:20,678", "msecs": 678.5111427307129, "relative_created": 2707.9758644104004, "process": 1, "message": "Logging to a Sentry instance is turned off"}
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.advise_justification.investigate_advise_justification' found in sys.modules after import of package 'investigator.investigator.advise_justification', but prior to execution of 'investigator.investigator.advise_justification.investigate_advise_justification'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.adviser_re_run.investigate_adviser_re_run' found in sys.modules after import of package 'investigator.investigator.adviser_re_run', but prior to execution of 'investigator.investigator.adviser_re_run.investigate_adviser_re_run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.adviser_trigger.investigate_adviser_trigger' found in sys.modules after import of package 'investigator.investigator.adviser_trigger', but prior to execution of 'investigator.investigator.adviser_trigger.investigate_adviser_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.hash_mismatch.investigate_hash_mismatch' found in sys.modules after import of package 'investigator.investigator.hash_mismatch', but prior to execution of 'investigator.investigator.hash_mismatch.investigate_hash_mismatch'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.kebechet_run_url_trigger.investigate_kebechet_run_url_trigger' found in sys.modules after import of package 'investigator.investigator.kebechet_run_url_trigger', but prior to execution of 'investigator.investigator.kebechet_run_url_trigger.investigate_kebechet_run_url_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.kebechet_trigger.investigate_kebechet_trigger' found in sys.modules after import of package 'investigator.investigator.kebechet_trigger', but prior to execution of 'investigator.investigator.kebechet_trigger.investigate_kebechet_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.missing_package.investigate_missing_package' found in sys.modules after import of package 'investigator.investigator.missing_package', but prior to execution of 'investigator.investigator.missing_package.investigate_missing_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.missing_version.investigate_missing_version' found in sys.modules after import of package 'investigator.investigator.missing_version', but prior to execution of 'investigator.investigator.missing_version.investigate_missing_version'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.package_extract_trigger.investigate_package_extract_trigger' found in sys.modules after import of package 'investigator.investigator.package_extract_trigger', but prior to execution of 'investigator.investigator.package_extract_trigger.investigate_package_extract_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.package_released.investigate_package_released' found in sys.modules after import of package 'investigator.investigator.package_released', but prior to execution of 'investigator.investigator.package_released.investigate_package_released'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.provenance_checker_trigger.investigate_provenance_checker_trigger' found in sys.modules after import of package 'investigator.investigator.provenance_checker_trigger', but prior to execution of 'investigator.investigator.provenance_checker_trigger.investigate_provenance_checker_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.qebhwt_trigger.investigate_qebhwt_trigger' found in sys.modules after import of package 'investigator.investigator.qebhwt_trigger', but prior to execution of 'investigator.investigator.qebhwt_trigger.investigate_qebhwt_trigger'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.si_unanalyzed_package.investigate_si_unanalyzed_package' found in sys.modules after import of package 'investigator.investigator.si_unanalyzed_package', but prior to execution of 'investigator.investigator.si_unanalyzed_package.investigate_si_unanalyzed_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.solved_package.investigate_solved_package' found in sys.modules after import of package 'investigator.investigator.solved_package', but prior to execution of 'investigator.investigator.solved_package.investigate_solved_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.unresolved_package.investigate_unresolved_package' found in sys.modules after import of package 'investigator.investigator.unresolved_package', but prior to execution of 'investigator.investigator.unresolved_package.investigate_unresolved_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.unrevsolved_package.investigate_unrevsolved_package' found in sys.modules after import of package 'investigator.investigator.unrevsolved_package', but prior to execution of 'investigator.investigator.unrevsolved_package.investigate_unrevsolved_package'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib64/python3.6/runpy.py:125: RuntimeWarning: 'investigator.investigator.update_provide_source_distro.investigate_update_provide_source_distro' found in sys.modules after import of package 'investigator.investigator.update_provide_source_distro', but prior to execution of 'investigator.investigator.update_provide_source_distro.investigate_update_provide_source_distro'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1604498661.1439037, "asctime": "2020-11-04 14:04:21,143", "msecs": 143.9037322998047, "relative_created": 3173.368453979492, "process": 1, "message": "Logging to a Sentry instance is turned off"}
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1604498661.1439037, "asctime": "2020-11-04 14:04:21,143", "msecs": 143.9037322998047, "relative_created": 3173.368453979492, "process": 1, "message": "Logging to a Sentry instance is turned off"}
{"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 158, "funcname": "__init__", "created": 1604498661.1669736, "asctime": "2020-11-04 14:04:21,166", "msecs": 166.97359085083008, "relative_created": 3196.4383125305176, "process": 1, "message": "TLS verification when communicating with k8s/okd master is disabled"}
{"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 158, "funcname": "__init__", "created": 1604498661.1669736, "asctime": "2020-11-04 14:04:21,166", "msecs": 166.97359085083008, "relative_created": 3196.4383125305176, "process": 1, "message": "TLS verification when communicating with k8s/okd master is disabled"}
%3|1604498664.592|FAIL|rdkafka#consumer-3| [thrd:ssl://thoth-kafka-0-aicoe.apps.ocp.prod.psi.redhat.com:443/0]: ssl://thoth-kafka-0-aicoe.apps.ocp.prod.psi.redhat.com:443/0: SSL handshake failed: Disconnected: connecting to a PLAINTEXT broker listener? (after 4ms in state CONNECT)
%3|1604498664.705|FAIL|rdkafka#consumer-3| [thrd:ssl://thoth-kafka-0-aicoe.apps.ocp.prod.psi.redhat.com:443/0]: ssl://thoth-kafka-0-aicoe.apps.ocp.prod.psi.redhat.com:443/0: SSL handshake failed: Disconnected: connecting to a PLAINTEXT broker listener? (after 1ms in state CONNECT, 1 identical error(s) suppressed)
Traceback (most recent call last):
  File "consumer.py", line 182, in <module>
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "consumer.py", line 143, in _confluent_consumer_loop
    raise KafkaException(msg.error())
cimpl.KafkaException: KafkaError{code=_SSL,val=-181,str="Failed to query logical offset END: Local: SSL error"}
```

**Additional context**

**Comment by harshad16** [comment]
The issue occurred due to Kafka broker failure. 
One of the Kafka brokers was in a terminating state and was stuck at that state. We have seen this happening in other application pods, this happens if suddenly the cluster node on which the pod was running is terminated. It causes the pods to attach to that node to be stuck.
As Kafka broker is a stateful set, it doesn't spin up any new pods until the old pods are deleted successfully. At this point, the broker is in an orphan state, so we have delete it forcefully from the cluster, for a new broker pod to start.
`oc delete pods thoth-kafka-0 --grace-period 0 --force`
Similar to the Kafka broker, another zookeeper pod was facing a similar issue. It also had to be removed from the cluster namespace.

Once this was executed, the Kafka broker 0, started another pod. However, it was unable to connect to the zookeeper nodes present in the cluster namespace, causing the broker to crash loop.
To fix this issue, Perform deletion of the zookeeper pods one by one and then refreshed the Kafka broker pods.
The Kafka broker pod was successfully able to connect with other zookeeper nodes.


As we didn't have persistent storage setup for the Kafka deployment, the topic message was deleted/lost , only the topic was retained due to the other Kafka broker.
The next step is to set up persistent storage for the Kafka deployment.

**Comment by harshad16** [comment]
The persistence was added to the kafka broker component.
Closing this issue
