### ISSUE TITLE
FileNotFoundError: No source distribution found for cloc task only in SI workflow

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#659]
**Describe the bug**
FileNotFoundError: No source distribution found for cloc task only. Why bandit did not fail and cloc yes?

**To Reproduce**
1. Reschedule same package for SI worklfow

**Expected behavior**
This error should be handled on the first task. 

**Screenshots**
```
argo watch security-indicator-2f24f8f7

Name:                security-indicator-2f24f8f7
Namespace:           thoth-middletier-stage
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Wed Nov 18 15:42:11 +0100 (12 minutes ago)
Started:             Wed Nov 18 15:53:58 +0100 (1 minute ago)
Finished:            Wed Nov 18 15:54:53 +0100 (17 seconds ago)
Duration:            55 seconds
ResourcesDuration:   1m23s*(1 cpu),4m35s*(100Mi memory)
Parameters:          
  ceph_bucket_prefix: data
  ceph_bucket_name:  thoth
  ceph_host:         s3.upshift.redhat.com
  deployment_name:   ocp-stage
  THOTH_SECURITY_INDICATORS_JOB_ID: security-indicator-2f24f8f7
  THOTH_DOCUMENT_ID: security-indicator-2f24f8f7
  THOTH_SECURITY_INDICATORS_PACKAGE_NAME: collective.nitf
  THOTH_SECURITY_INDICATORS_PACKAGE_VERSION: 1.0b1
  THOTH_SECURITY_INDICATORS_PACKAGE_INDEX: https://pypi.org/simple
  THOTH_SECURITY_INDICATORS_AGGREGATION_FUNCTION: process_data
  THOTH_FORCE_SYNC:  0

STEP                                   TEMPLATE                           PODNAME                                 DURATION  MESSAGE
 ✖ security-indicator-2f24f8f7         security-indicators                                                                                                 
 ├-✔ download-package                  download-package/download-package  security-indicator-2f24f8f7-3161282592  26s                                      
 ├-✔ bandit                            bandit/bandit-from-dir             security-indicator-2f24f8f7-3463513711  21s                                      
 ├-✖ cloc                              cloc/cloc-from-dir                 security-indicator-2f24f8f7-3588734096  21s       failed with exit code 1        
 ├-○ send-messages                     send-messages/send-messages                                                          when '0 == 1' evaluated false  
                                                                                                                                                                    
 ✔ security-indicator-2f24f8f7.onExit  exit-handler                                                                                                        
 └---✔ delete-pvc                      delete-pvc                         security-indicator-2f24f8f7-3924150481  4s                                       
 fmurdaca@pc-7  ~/work/aicoe/jupyterlab-requirements   master ●  argo logs -f security-indicator-2f24f8f7
security-indicator-2f24f8f7-3161282592: 2020-11-18T14:54:14.582631809Z {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1605711254.5821936, "asctime": "2020-11-18 14:54:14,582", "msecs": 582.1936130523682, "relative_created": 6498.187065124512, "process": 1, "message": "Logging to a Sentry instance is turned off"}
security-indicator-2f24f8f7-3463513711: 2020-11-18T14:54:37.164057Z 2020-11-18 14:54:37,163   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-2f24f8f7-3463513711: 2020-11-18T14:54:37.164057Z 2020-11-18 14:54:37,163   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:40.289292568Z 2020-11-18 14:54:40,289   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:40.289292568Z 2020-11-18 14:54:40,289   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:40.289443096Z 2020-11-18 14:54:40,289   1 INFO     si-cloc:39: SI Cloc v0.1.3+analyzer.0.1.8.common.0.19.0.
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z 2020-11-18 14:54:44,585   1 CRITICAL root:101: Traceback (most recent call last):
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z     return self.main(*args, **kwargs)
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z     rv = self.invoke(ctx)
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z     return callback(*args, **kwargs)
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z     __name__ == "__main__" and si_cloc()
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z     return f(get_current_context(), *args, **kwargs)
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z   File "app.py", line 95, in si_cloc
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z     raise FileNotFoundError(
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z FileNotFoundError: No source distribution found for collective.nitf===1.0b1 on https://pypi.org/simple
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z 
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z   File "app.py", line 116, in <module>
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z     return ctx.invoke(self.callback, **ctx.params)
security-indicator-2f24f8f7-3588734096: 2020-11-18T14:54:44.585861861Z   File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 21, in new_func
security-indicator-2f24f8f7-3463513711: 2020-11-18T14:54:44.878634864Z 2020-11-18 14:54:44,877   1 INFO     thoth.analyzer.cli:175: Writing results to '/mnt/workdir/bandit_results'
security-indicator-2f24f8f7-3924150481: 2020-11-18T14:54:51.268105381Z time="2020-11-18T14:54:51.267Z" level=info msg="Starting Workflow Executor" version=v2.11.0
security-indicator-2f24f8f7-3924150481: 2020-11-18T14:54:51.275876304Z time="2020-11-18T14:54:51.275Z" level=info msg="Creating a K8sAPI executor"
security-indicator-2f24f8f7-3924150481: 2020-11-18T14:54:51.275921478Z time="2020-11-18T14:54:51.275Z" level=info msg="Executor (version: v2.11.0, build_date: 2020-09-17T22:51:06Z) initialized (pod: thoth-middletier-stage/security-indicator-2f24f8f7-3924150481) with template:\n{\"name\":\"delete-pvc\",\"arguments\":{},\"inputs\":{},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"delete\",\"manifest\":\"apiVersion: v1\\nkind: PersistentVolumeClaim\\nmetadata:\\n  name: security-indicator-2f24f8f7-workdir\\n\"}}"
security-indicator-2f24f8f7-3924150481: 2020-11-18T14:54:51.275921478Z time="2020-11-18T14:54:51.275Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
security-indicator-2f24f8f7-3924150481: 2020-11-18T14:54:51.276391284Z time="2020-11-18T14:54:51.276Z" level=info msg="kubectl delete --ignore-not-found -f /tmp/manifest.yaml -o name"

```

**Additional context**

**Comment by goern** [comment]
@pacospace what is the status of this?

**Comment by pacospace** [comment]
> @pacospace what is the status of this?

@KPostOffice

**Comment by KPostOffice** [comment]
Fixed by https://github.com/thoth-station/thoth-application/pull/666
