### ISSUE TITLE
Security workflow does not sends message when erro FileNotFoundError: No source distribution found is raised

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#660]
**Describe the bug**
Security workflow in some cases does not sends a message when error `FileNotFoundError: No source distribution found` is raised

**To Reproduce**
1. Reschedule same package for SI worklfow

**Expected behavior**
Message is sent to that investigator can mark that package missing distro and do not schedule that again

**Screenshots**
```
argo logs -f security-indicator-18ee3c64
security-indicator-18ee3c64-981673176: 2020-11-18T14:56:04.624020611Z {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1605711364.6235762, "asctime": "2020-11-18 14:56:04,623", "msecs": 623.5761642456055, "relative_created": 5602.884292602539, "process": 1, "message": "Logging to a Sentry instance is turned off"}
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:24.425368114Z 2020-11-18 14:56:24,425   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:24.425368114Z 2020-11-18 14:56:24,425   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:24.425501529Z 2020-11-18 14:56:24,425   1 INFO     si-cloc:39: SI Cloc v0.1.3+analyzer.0.1.8.common.0.19.0.
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z FileNotFoundError: No source distribution found for plone.rfc822===1.0b2 on https://pypi.org/simple
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z 2020-11-18 14:56:28,727   1 CRITICAL root:101: Traceback (most recent call last):
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z   File "app.py", line 116, in <module>
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z     __name__ == "__main__" and si_cloc()
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z     return self.main(*args, **kwargs)
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z     return f(get_current_context(), *args, **kwargs)
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z     rv = self.invoke(ctx)
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z     return ctx.invoke(self.callback, **ctx.params)
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z     return callback(*args, **kwargs)
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z   File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 21, in new_func
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z     raise FileNotFoundError(
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z 
security-indicator-18ee3c64-2750028424: 2020-11-18T14:56:28.727787887Z   File "app.py", line 95, in si_cloc
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:35.17846216Z 2020-11-18 14:56:35,177   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:35.17846216Z 2020-11-18 14:56:35,178   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z 2020-11-18 14:56:37,668   1 CRITICAL root:102: Traceback (most recent call last):
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z     out = _run_bandit(from_directory)
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z   File "app.py", line 59, in _run_bandit
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z     raise Exception(out["errors"])
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z Exception: [{'filename': '/mnt/workdir/package/plone.rfc822-1.0b2/plone/rfc822/_utils.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/plone.rfc822-1.0b2/plone/rfc822/defaultfields.py', 'reason': 'syntax error while parsing AST from file'}]
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z   File "app.py", line 124, in si_bandit
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z   File "app.py", line 150, in <module>
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z     __name__ == "__main__" and si_bandit()
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z     return self.main(*args, **kwargs)
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z     rv = self.invoke(ctx)
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z     return ctx.invoke(self.callback, **ctx.params)
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z     return callback(*args, **kwargs)
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z   File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z     return f(get_current_context(), *args, **kwargs)
security-indicator-18ee3c64-1094141959: 2020-11-18T14:56:37.668498684Z 
security-indicator-18ee3c64-2262997913: 2020-11-18T14:56:44.728210221Z time="2020-11-18T14:56:44.727Z" level=info msg="Starting Workflow Executor" version=v2.11.0
security-indicator-18ee3c64-2262997913: 2020-11-18T14:56:44.732144261Z time="2020-11-18T14:56:44.732Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
security-indicator-18ee3c64-2262997913: 2020-11-18T14:56:44.732144261Z time="2020-11-18T14:56:44.732Z" level=info msg="Creating a K8sAPI executor"
security-indicator-18ee3c64-2262997913: 2020-11-18T14:56:44.732144261Z time="2020-11-18T14:56:44.732Z" level=info msg="Executor (version: v2.11.0, build_date: 2020-09-17T22:51:06Z) initialized (pod: thoth-middletier-stage/security-indicator-18ee3c64-2262997913) with template:\n{\"name\":\"delete-pvc\",\"arguments\":{},\"inputs\":{},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"delete\",\"manifest\":\"apiVersion: v1\\nkind: PersistentVolumeClaim\\nmetadata:\\n  name: security-indicator-18ee3c64-workdir\\n\"}}"
security-indicator-18ee3c64-2262997913: 2020-11-18T14:56:44.732603885Z time="2020-11-18T14:56:44.732Z" level=info msg="kubectl delete --ignore-not-found -f /tmp/manifest.yaml -o name"
 fmurdaca@pc-7  ~/work/aicoe/jupyterlab-requirements   master ●  argo watch security-indicator-18ee3c64


Name:                security-indicator-18ee3c64
Namespace:           thoth-middletier-stage
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Wed Nov 18 15:48:40 +0100 (8 minutes ago)
Started:             Wed Nov 18 15:55:35 +0100 (1 minute ago)
Finished:            Wed Nov 18 15:56:46 +0100 (19 seconds ago)
Duration:            1 minute 11 seconds
ResourcesDuration:   1m15s*(1 cpu),4m16s*(100Mi memory)
Parameters:          
  ceph_bucket_prefix: data
  ceph_bucket_name:  thoth
  ceph_host:         s3.upshift.redhat.com
  deployment_name:   ocp-stage
  THOTH_SECURITY_INDICATORS_JOB_ID: security-indicator-18ee3c64
  THOTH_DOCUMENT_ID: security-indicator-18ee3c64
  THOTH_SECURITY_INDICATORS_PACKAGE_NAME: plone.rfc822
  THOTH_SECURITY_INDICATORS_PACKAGE_VERSION: 1.0b2
  THOTH_SECURITY_INDICATORS_PACKAGE_INDEX: https://pypi.org/simple
  THOTH_SECURITY_INDICATORS_AGGREGATION_FUNCTION: process_data
  THOTH_FORCE_SYNC:  0

STEP                                   TEMPLATE                           PODNAME                                 DURATION  MESSAGE
 ✖ security-indicator-18ee3c64         security-indicators                                                                                                 
 ├-✔ download-package                  download-package/download-package  security-indicator-18ee3c64-981673176   36s                                      
 ├-✖ bandit                            bandit/bandit-from-dir             security-indicator-18ee3c64-1094141959  26s       failed with exit code 1        
 ├-✖ cloc                              cloc/cloc-from-dir                 security-indicator-18ee3c64-2750028424  17s       failed with exit code 1        
 ├-○ send-messages                     send-messages/send-messages                                                          when '0 == 1' evaluated false  
                                                                                                                                                                    
 ✔ security-indicator-18ee3c64.onExit  exit-handler                                                                                                        
 └---✔ delete-pvc                      delete-pvc                         security-indicator-18ee3c64-2262997913  4s    
```

**Additional context**

**Comment by KPostOffice** [comment]
I don't know why `si-cloc` is failing to find source distribution after `download-package` succeeds, but it should be fixed by [this](https://github.com/thoth-station/thoth-application/pull/666) pull request

**Comment by KPostOffice** [comment]
Other than that this seems to work as intended. `download package` succeeds, a message should only be sent if this step fails.

**Comment by goern** [comment]
@KPostOffice @pacospace how do we conclude this issue?

**Comment by pacospace** [comment]
> @KPostOffice @pacospace how do we conclude this issue?

I believe it can be closed from @KPostOffice comments
