### ISSUE TITLE
si cloc task in SI workflow fails handling errors and prevent from sending message to avoid rescheduling Si workflow

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#661]
**Describe the bug**
si cloc task in SI workflow fails handling errors and prevent from sending message to avoid rescheduling Si workflow

**To Reproduce**
1. Reschedule same package for SI worklfow

**Expected behavior**
Message should be sent to investigator and synced and no same workflow should be rescheduled.

**Screenshots**
```
argo watch security-indicator-bccf7157

Name:                security-indicator-bccf7157
Namespace:           thoth-middletier-stage
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Wed Nov 18 15:34:52 +0100 (19 minutes ago)
Started:             Wed Nov 18 15:52:52 +0100 (1 minute ago)
Finished:            Wed Nov 18 15:54:09 +0100 (13 seconds ago)
Duration:            1 minute 17 seconds
ResourcesDuration:   1m17s*(1 cpu),4m14s*(100Mi memory)
Parameters:          
  ceph_bucket_prefix: data
  ceph_bucket_name:  thoth
  ceph_host:         s3.upshift.redhat.com
  deployment_name:   ocp-stage
  THOTH_SECURITY_INDICATORS_JOB_ID: security-indicator-bccf7157
  THOTH_DOCUMENT_ID: security-indicator-bccf7157
  THOTH_SECURITY_INDICATORS_PACKAGE_NAME: collective.indexing
  THOTH_SECURITY_INDICATORS_PACKAGE_VERSION: 1.0rc3
  THOTH_SECURITY_INDICATORS_PACKAGE_INDEX: https://pypi.org/simple
  THOTH_SECURITY_INDICATORS_AGGREGATION_FUNCTION: process_data
  THOTH_FORCE_SYNC:  0

STEP                                   TEMPLATE                           PODNAME                                 DURATION  MESSAGE
 ✖ security-indicator-bccf7157         security-indicators                                                                                                 
 ├-✔ download-package                  download-package/download-package  security-indicator-bccf7157-22730035    38s                                      
 ├-✖ bandit                            bandit/bandit-from-dir             security-indicator-bccf7157-2260335612  31s       failed with exit code 1        
 ├-✖ cloc                              cloc/cloc-from-dir                 security-indicator-bccf7157-378793007   30s       failed with exit code 1        
 ├-○ send-messages                     send-messages/send-messages                                                          when '0 == 1' evaluated false  
                                                                                                                                                                    
 ✔ security-indicator-bccf7157.onExit  exit-handler                                                                                                        
 └---✔ delete-pvc                      delete-pvc                         security-indicator-bccf7157-3153503414  4s                                       
 fmurdaca@pc-7  ~/work/aicoe/jupyterlab-requirements   master ●  argo logs -f security-indicator-bccf7157
security-indicator-bccf7157-22730035: 2020-11-18T14:53:20.642644857Z {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1605711200.6421976, "asctime": "2020-11-18 14:53:20,642", "msecs": 642.1976089477539, "relative_created": 6410.198926925659, "process": 1, "message": "Logging to a Sentry instance is turned off"}
security-indicator-bccf7157-378793007: 2020-11-18T14:53:55.082763505Z 2020-11-18 14:53:55,082   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-bccf7157-378793007: 2020-11-18T14:53:55.082763505Z 2020-11-18 14:53:55,082   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-bccf7157-378793007: 2020-11-18T14:53:55.082899636Z 2020-11-18 14:53:55,082   1 INFO     si-cloc:39: SI Cloc v0.1.3+analyzer.0.1.8.common.0.19.0.
security-indicator-bccf7157-2260335612: 2020-11-18T14:53:57.193174521Z 2020-11-18 14:53:57,192   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-bccf7157-2260335612: 2020-11-18T14:53:57.193174521Z 2020-11-18 14:53:57,193   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z     return f(get_current_context(), *args, **kwargs)
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z     return ctx.invoke(self.callback, **ctx.params)
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z     rv = self.invoke(ctx)
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z FileNotFoundError: No source distribution found for collective.indexing===1.0rc3 on https://pypi.org/simple
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z     return self.main(*args, **kwargs)
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z     raise FileNotFoundError(
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z   File "app.py", line 95, in si_cloc
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z 
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z   File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z     __name__ == "__main__" and si_cloc()
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z   File "app.py", line 116, in <module>
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z   File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 21, in new_func
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z 2020-11-18 14:54:00,878   1 CRITICAL root:101: Traceback (most recent call last):
security-indicator-bccf7157-378793007: 2020-11-18T14:54:00.878680874Z     return callback(*args, **kwargs)
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z     return f(get_current_context(), *args, **kwargs)
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z     out = _run_bandit(from_directory)
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z   File "app.py", line 59, in _run_bandit
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z     raise Exception(out["errors"])
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z Exception: [{'filename': '/mnt/workdir/package/collective.indexing-1.0rc3/collective/indexing/queue.py', 'reason': 'syntax error while parsing AST from file'}]
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z 
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z   File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z     return ctx.invoke(self.callback, **ctx.params)
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z     rv = self.invoke(ctx)
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z     __name__ == "__main__" and si_bandit()
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z   File "app.py", line 150, in <module>
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z 2020-11-18 14:54:01,283   1 CRITICAL root:102: Traceback (most recent call last):
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z     return callback(*args, **kwargs)
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z   File "app.py", line 124, in si_bandit
security-indicator-bccf7157-2260335612: 2020-11-18T14:54:01.283897097Z     return self.main(*args, **kwargs)
security-indicator-bccf7157-3153503414: 2020-11-18T14:54:08.377190145Z time="2020-11-18T14:54:08.376Z" level=info msg="Starting Workflow Executor" version=v2.11.0
security-indicator-bccf7157-3153503414: 2020-11-18T14:54:08.382355655Z time="2020-11-18T14:54:08.382Z" level=info msg="Executor (version: v2.11.0, build_date: 2020-09-17T22:51:06Z) initialized (pod: thoth-middletier-stage/security-indicator-bccf7157-3153503414) with template:\n{\"name\":\"delete-pvc\",\"arguments\":{},\"inputs\":{},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"delete\",\"manifest\":\"apiVersion: v1\\nkind: PersistentVolumeClaim\\nmetadata:\\n  name: security-indicator-bccf7157-workdir\\n\"}}"
security-indicator-bccf7157-3153503414: 2020-11-18T14:54:08.382355655Z time="2020-11-18T14:54:08.382Z" level=info msg="Creating a K8sAPI executor"
security-indicator-bccf7157-3153503414: 2020-11-18T14:54:08.382388763Z time="2020-11-18T14:54:08.382Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
security-indicator-bccf7157-3153503414: 2020-11-18T14:54:08.382774272Z time="2020-11-18T14:54:08.382Z" level=info msg="kubectl delete --ignore-not-found -f /tmp/manifest.yaml -o name"

```

**Additional context**

**Comment by KPostOffice** [comment]
This should be fixed with new release
