### ISSUE TITLE
errors should be collected so that same Si workflow should not be scheduled

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#662]
**Describe the bug**
errors should be collected so that same Si workflow should not be scheduled

**To Reproduce**
1. Reschedule same package for SI workflow

**Expected behavior**
Failure in any of the task in SI workflow, still allow for sending message so that workflow is not rescheduled.

**Screenshots**
```
argo watch security-indicator-29282d83

Name:                security-indicator-29282d83
Namespace:           thoth-middletier-stage
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Wed Nov 18 16:01:11 +0100 (11 minutes ago)
Started:             Wed Nov 18 16:10:19 +0100 (2 minutes ago)
Finished:            Wed Nov 18 16:12:47 +0100 (17 seconds ago)
Duration:            2 minutes 28 seconds
ResourcesDuration:   4m46s*(1 cpu),15m44s*(100Mi memory)
Parameters:          
  ceph_bucket_prefix: data
  ceph_bucket_name:  thoth
  ceph_host:         s3.upshift.redhat.com
  deployment_name:   ocp-stage
  THOTH_SECURITY_INDICATORS_JOB_ID: security-indicator-29282d83
  THOTH_DOCUMENT_ID: security-indicator-29282d83
  THOTH_SECURITY_INDICATORS_PACKAGE_NAME: networkx
  THOTH_SECURITY_INDICATORS_PACKAGE_VERSION: 1.4
  THOTH_SECURITY_INDICATORS_PACKAGE_INDEX: https://pypi.org/simple
  THOTH_SECURITY_INDICATORS_AGGREGATION_FUNCTION: process_data
  THOTH_FORCE_SYNC:  0

STEP                                   TEMPLATE                           PODNAME                                 DURATION  MESSAGE
 ✖ security-indicator-29282d83         security-indicators                                                                                                 
 ├-✔ download-package                  download-package/download-package  security-indicator-29282d83-1553631269  31s                                      
 ├-✖ bandit                            bandit/bandit-from-dir             security-indicator-29282d83-3587015418  1m        failed with exit code 1        
 ├-✔ cloc                              cloc/cloc-from-dir                 security-indicator-29282d83-2128191041  25s                                      
 ├-○ send-messages                     send-messages/send-messages                                                          when '0 == 1' evaluated false  
                                                                                                                                                                    
 ✔ security-indicator-29282d83.onExit  exit-handler                                                                                                        
 └---✔ delete-pvc                      delete-pvc                         security-indicator-29282d83-1437351044  3s                                       
 fmurdaca@pc-7  ~/work/aicoe/jupyterlab-requirements   master ●  argo logs -f security-indicator-29282d83
security-indicator-29282d83-1553631269: 2020-11-18T15:10:38.167892754Z {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1605712238.1672893, "asctime": "2020-11-18 15:10:38,167", "msecs": 167.28925704956055, "relative_created": 7700.979709625244, "process": 1, "message": "Logging to a Sentry instance is turned off"}
security-indicator-29282d83-2128191041: 2020-11-18T15:11:04.471167958Z 2020-11-18 15:11:04,471   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-29282d83-2128191041: 2020-11-18T15:11:04.471167958Z 2020-11-18 15:11:04,470   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-29282d83-2128191041: 2020-11-18T15:11:04.47137975Z 2020-11-18 15:11:04,471   1 INFO     si-cloc:39: SI Cloc v0.1.3+analyzer.0.1.8.common.0.19.0.
security-indicator-29282d83-3587015418: 2020-11-18T15:11:05.282038958Z 2020-11-18 15:11:05,281   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-29282d83-3587015418: 2020-11-18T15:11:05.282038958Z 2020-11-18 15:11:05,281   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-29282d83-2128191041: 2020-11-18T15:11:16.764896889Z 2020-11-18 15:11:16,764   1 INFO     thoth.analyzer.cli:175: Writing results to '/mnt/workdir/cloc_results'
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z     rv = self.invoke(ctx)
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z     return ctx.invoke(self.callback, **ctx.params)
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z     return callback(*args, **kwargs)
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z   File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z     return f(get_current_context(), *args, **kwargs)
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z     return self.main(*args, **kwargs)
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z     out = _run_bandit(from_directory)
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z   File "app.py", line 59, in _run_bandit
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z     raise Exception(out["errors"])
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z Exception: [{'filename': '/mnt/workdir/package/networkx-1.4/doc/make_examples_rst.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/doc/make_gallery.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/doc/sphinxext/customroles.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/doc/sphinxext/docscrape.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/doc/sphinxext/numpydoc.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/examples/drawing/degree_histogram.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/examples/drawing/giant_component.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/examples/drawing/lanl_routes.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/examples/pygraphviz/write_dotfile.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/scripts/adjlist2edgelist.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/scripts/adjmat2edgelist.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/scripts/bipartiteadjmat2edgelist.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/scripts/docdiff.py', 'reason': 'syntax error while parsing AST from file'}, {'filename': '/mnt/workdir/package/networkx-1.4/scripts/edgelist2adjlist.py', 'reason': 'syntax error while parsing AST from file'}]
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z 
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z 2020-11-18 15:12:39,579   1 CRITICAL root:102: Traceback (most recent call last):
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z   File "app.py", line 150, in <module>
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z     __name__ == "__main__" and si_bandit()
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
security-indicator-29282d83-3587015418: 2020-11-18T15:12:39.667485551Z   File "app.py", line 124, in si_bandit
security-indicator-29282d83-1437351044: 2020-11-18T15:12:46.225998541Z time="2020-11-18T15:12:46.225Z" level=info msg="Starting Workflow Executor" version=v2.11.0
security-indicator-29282d83-1437351044: 2020-11-18T15:12:46.22950345Z time="2020-11-18T15:12:46.229Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
security-indicator-29282d83-1437351044: 2020-11-18T15:12:46.22950345Z time="2020-11-18T15:12:46.229Z" level=info msg="Executor (version: v2.11.0, build_date: 2020-09-17T22:51:06Z) initialized (pod: thoth-middletier-stage/security-indicator-29282d83-1437351044) with template:\n{\"name\":\"delete-pvc\",\"arguments\":{},\"inputs\":{},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"delete\",\"manifest\":\"apiVersion: v1\\nkind: PersistentVolumeClaim\\nmetadata:\\n  name: security-indicator-29282d83-workdir\\n\"}}"
security-indicator-29282d83-1437351044: 2020-11-18T15:12:46.22950345Z time="2020-11-18T15:12:46.229Z" level=info msg="Creating a K8sAPI executor"
security-indicator-29282d83-1437351044: 2020-11-18T15:12:46.229775127Z time="2020-11-18T15:12:46.229Z" level=info msg="kubectl delete --ignore-not-found -f /tmp/manifest.yaml -o name"

```

**Additional context**

**Comment by KPostOffice** [comment]
Errors in `si-cloc` and `si-bandit` should be handled by `graph-sync` now.
