### ISSUE TITLE
SI workflow failing because `NameError: name 'unicode' is not defined`

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#663]
**Describe the bug**
SI workflow failing because `NameError: name 'unicode' is not defined`

**To Reproduce**
1. Reschedule similar package for SI workflow

**Expected behavior**
Learn from errors

**Screenshots**
```
argo watch security-indicator-3d59d230

Name:                security-indicator-3d59d230
Namespace:           thoth-middletier-stage
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Wed Nov 18 16:02:20 +0100 (21 minutes ago)
Started:             Wed Nov 18 16:22:54 +0100 (57 seconds ago)
Finished:            Wed Nov 18 16:23:41 +0100 (10 seconds ago)
Duration:            47 seconds
ResourcesDuration:   43s*(1 cpu),2m24s*(100Mi memory)
Parameters:          
  ceph_bucket_prefix: data
  ceph_bucket_name:  thoth
  ceph_host:         s3.upshift.redhat.com
  deployment_name:   ocp-stage
  THOTH_SECURITY_INDICATORS_JOB_ID: security-indicator-3d59d230
  THOTH_DOCUMENT_ID: security-indicator-3d59d230
  THOTH_SECURITY_INDICATORS_PACKAGE_NAME: zest-releaser
  THOTH_SECURITY_INDICATORS_PACKAGE_VERSION: 3.29
  THOTH_SECURITY_INDICATORS_PACKAGE_INDEX: https://pypi.org/simple
  THOTH_SECURITY_INDICATORS_AGGREGATION_FUNCTION: process_data
  THOTH_FORCE_SYNC:  0

STEP                                   TEMPLATE                           PODNAME                                 DURATION  MESSAGE
 ✖ security-indicator-3d59d230         security-indicators                                                                                           
 ├-✖ download-package                  download-package/download-package  security-indicator-3d59d230-2410953425  37s       failed with exit code 1  
                                                                                                                                                              
 ✔ security-indicator-3d59d230.onExit  exit-handler                                                                                                  
 └---✔ delete-pvc                      delete-pvc                         security-indicator-3d59d230-3449924304  4s                                 
 fmurdaca@pc-7  ~/work/aicoe/jupyterlab-requirements   master ●  argo logs -f security-indicator-3d59d230
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:22.614452154Z {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1605713002.6139374, "asctime": "2020-11-18 15:23:22,613", "msecs": 613.9373779296875, "relative_created": 8850.142002105713, "process": 1, "message": "Logging to a Sentry instance is turned off"}
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.567495857Z Traceback (most recent call last):
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.567495857Z   File "download_py_package.py", line 138, in <module>
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.567827082Z   File "download_py_package.py", line 117, in download_py_package
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.567827082Z     download_py_package()
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.567914154Z   File "/opt/app-root/lib/python3.6/site-packages/thoth/analyzer/command.py", line 107, in run_command
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.567914154Z     run_command(command)
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568055637Z     raise CommandError(error_msg, command=command, is_json=is_json)
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z 
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z         return unicode(codecs.open(filename, encoding='utf-8').read())
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z     NameError: name 'unicode' is not defined
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z     ----------------------------------------
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z         long_description = '\n\n'.join([read('README.txt'),
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z      command: /opt/app-root/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-download-d2qaub4p/zest-releaser/setup.py'"'"'; __file__='"'"'/tmp/pip-download-d2qaub4p/zest-releaser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1pg1flhj
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z          cwd: /tmp/pip-download-d2qaub4p/zest-releaser/
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z     Complete output (7 lines):
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z     Traceback (most recent call last):
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z       File "<string>", line 1, in <module>
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z       File "/tmp/pip-download-d2qaub4p/zest-releaser/setup.py", line 17, in <module>
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z thoth.analyzer.command.CommandError: Command exited with non-zero status code (1):     ERROR: Command errored out with exit status 1:
security-indicator-3d59d230-2410953425: 2020-11-18T15:23:30.568079336Z       File "/tmp/pip-download-d2qaub4p/zest-releaser/setup.py", line 10, in read
security-indicator-3d59d230-3449924304: 2020-11-18T15:23:38.824719712Z time="2020-11-18T15:23:38.824Z" level=info msg="Starting Workflow Executor" version=v2.11.0
security-indicator-3d59d230-3449924304: 2020-11-18T15:23:38.890932102Z time="2020-11-18T15:23:38.890Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
security-indicator-3d59d230-3449924304: 2020-11-18T15:23:38.890932102Z time="2020-11-18T15:23:38.890Z" level=info msg="Executor (version: v2.11.0, build_date: 2020-09-17T22:51:06Z) initialized (pod: thoth-middletier-stage/security-indicator-3d59d230-3449924304) with template:\n{\"name\":\"delete-pvc\",\"arguments\":{},\"inputs\":{},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"delete\",\"manifest\":\"apiVersion: v1\\nkind: PersistentVolumeClaim\\nmetadata:\\n  name: security-indicator-3d59d230-workdir\\n\"}}"
security-indicator-3d59d230-3449924304: 2020-11-18T15:23:38.890932102Z time="2020-11-18T15:23:38.890Z" level=info msg="Creating a K8sAPI executor"
security-indicator-3d59d230-3449924304: 2020-11-18T15:23:38.89130675Z time="2020-11-18T15:23:38.891Z" level=info msg="kubectl delete --ignore-not-found -f /tmp/manifest.yaml -o name"

```

**Additional context**

**Comment by KPostOffice** [comment]
This is due to this version of `zest.releaser` only being compatible with versions 2.X of Python but it is not stated in the PyPI Warehouse

**Comment by goern** [comment]
> This is due to this version of `zest.releaser` only being compatible with versions 2.X of Python but it is not stated in the PyPI Warehouse

Do we need to do something to close this issue?

**Comment by KPostOffice** [comment]
Inability to download should be marked in DB. Is this sufficient?

**Comment by pacospace** [comment]
> Inability to download should be marked in DB. Is this sufficient?

Yes think so, we can go back to these errors and check why they failed in the future to improve thoth on security knowledge level. 

Thanks @KPostOffice
