### ISSUE TITLE
Public bucket for Hue/Superset in cnv-prod does not exist as in stage environment

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#842]
**Describe the bug**
Public bucket for Hue/Superset on MOC is missing. This error is not critical, as SLO reporter in prod is storing in the correct thoth bucket, but have to check on Operate First how to handle Hue/Superset and correct the env variable. Moreover, a way to optionally store only in thoth bucket should be implemented, as the bucket n Operate First should be public already and therefore could be used in Hue/Superset on Operate First I assume.

**To Reproduce**
1. Run SLO reporter

**Expected behavior**

**Screenshots**
```
ERROR:thoth.slo_reporter:Could not store metrics on Public bucket on Ceph...An error occurred (NoSuchBucket) when calling the PutObject operation: Unknown
Traceback (most recent call last):
  File "app.py", line 190, in store_sli_periodic_metrics_to_ceph
    store_thoth_sli_on_ceph(
  File "/opt/app-root/src/thoth/slo_reporter/utils.py", line 174, in store_thoth_sli_on_ceph
    ceph_sli.store_blob(blob=metrics_csv, object_key=ceph_path)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/ceph.py", line 78, in store_blob
    response = self._s3.Object(self.bucket, f"{self.prefix}{object_key}").put(**put_kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: Unknown
```

**Additional context**

**Comment by pacospace** [comment]
Because of https://github.com/thoth-station/thoth-application/pull/1038, we can use internal Hue/Superset to have prod dashboard!!

**Comment by pacospace** [comment]
hey @xtuchyna what is the public bucket in Operate First for Hue/Superset?

**Comment by xtuchyna** [comment]
> hey @xtuchyna what is the public bucket in Operate First for Hue/Superset?

hey, the bucket name is `opf-datacatalog-dtuchyna` and you should have the credentials

**Comment by pacospace** [comment]
I'm closing this issues, as we have already: https://github.com/thoth-station/slo-reporter/issues/197
