### ISSUE TITLE
Container image analyses fail due to wrong output location

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#848]
**Describe the bug**

```
2021-02-02 19:51:31,369   1 INFO     thoth.analyzer.cli:175: Writing results to '/mnt/workdir/'
2021-02-02 19:51:31,398   1 CRITICAL root:105: Traceback (most recent call last):
  File "/usr/local/bin/thoth-package-extract", line 11, in <module>
    load_entry_point('thoth-package-extract==1.1.2', 'console_scripts', 'thoth-package-extract')()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/thoth_package_extract-1.1.2-py3.8.egg/thoth/package_extract/cli.py", line 178, in cli_extract_image
    print_command_result(
  File "/usr/local/lib/python3.8/site-packages/thoth/analyzer/cli.py", line 176, in print_command_result
    with open(output, "w") as output_file:
IsADirectoryError: [Errno 21] Is a directory: '/mnt/workdir/'
```

**To Reproduce**
1. Go to test/stage environment
2. Run package-extract
3. Check logs
4. See the error

**Expected behavior**

The container should write results to workdir location, in package-extract id file.

**Comment by fridex** [comment]
https://github.com/thoth-station/thoth-application/blob/35770a9c3f88d68dec4d6bb70f9d5f1418886dc5/package-extract/base/argo-workflows/package-extract.yaml#L62-L63

Looks like the document id is not correctly propagated:

```
      Name:              ceph_bucket_prefix
      Value:             data
      Name:              ceph_bucket_name
      Value:             thoth
      Name:              ceph_host
      Value:             s3.upshift.redhat.com
      Name:              deployment_name
      Value:             ocp4-stage
      Name:              THOTH_ANALYZED_IMAGE
      Value:             quay.io/thoth-station/s2i-thoth-f32-py38:v0.24.2
      Name:              THOTH_PACKAGE_EXTRACT_JOB_ID
      Value:             package-extract-e40888951e11108954ea5b41fca3821e
      Name:              THOTH_DOCUMENT_ID
      Value:             
      Name:              THOTH_LOG_PACKAGE_EXTRACT
      Value:             INFO
      Name:              THOTH_PACKAGE_EXTRACT_METADATA
      Value:             {"origin": null, "environment_type": "runtime", "is_external": false}
      Name:              THOTH_ANALYZER_NO_TLS_VERIFY
      Value:             0
      Name:              THOTH_REGISTRY_CREDENTIALS
      Value:             
```
