### ISSUE TITLE
thoth.common.exceptions.SolverNameParseError: Solver should be in a form of 'solver-<os_name>-<os_version>-<python_version>, solver name 'solver-rhel-8' does not correspond to this naming schema

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#941]
**Describe the bug**
```
Traceback (most recent call last):
  File "app.py", line 252, in <module>
    cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
{"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 222, "funcname": "_send_event", "created": 1613647572.4678545, "asctime": "2021-02-18 11:26:12,467", "msecs": 467.85449981689453, "relative_created": 11011.170625686646, "process": 1, "message": "Sending event, type:null level:error event_id:b64e34acc2f64bfc90b6dd79601d6263 project:1298083 host:sentry.io"}
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 226, in cli
    _do_sync(
  File "app.py", line 125, in _do_sync
    stats = sync_documents(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/sync.py", line 574, in sync_documents
    stats_change = handler(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/sync.py", line 131, in sync_solver_documents
    graph.sync_solver_result(document)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 4947, in sync_solver_result
    solver_info = OpenShift.parse_python_solver_name(solver_name)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/openshift.py", line 205, in parse_python_solver_name
    raise SolverNameParseError(
thoth.common.exceptions.SolverNameParseError: Solver should be in a form of 'solver-<os_name>-<os_version>-<python_version>, solver name 'solver-rhel-8' does not correspond to this naming schema
```

**To Reproduce**
1. Go to https://console-openshift-console.apps.cnv.massopen.cloud/k8s/ns/thoth-middletier-prod/pods/solver-rhel-8-py36-4d4fa0c4b679e57162e616eafb76742c-3727862951/logs?container=main

/kind bug
/label deployment/moc
/priority critical-urgent
/sig devops

**Comment by fridex** [comment]
This requires new graph-sync, the issue was already addressed in https://github.com/thoth-station/storages/pull/2207/files

**Comment by harshad16** [comment]
I feel like we should support both the old pattern and the new pattern in storages, as we might see think too many times running the sync-job, as we have a lot of old pattern documents in ceph.
we have total of 1591125 solver documents.Out of which:
1450563 documents (old pattern: solver-fedora-31-py37-0d512c50) 
140562 documents (new pattern: solver-fedora-32-py37-210220013058-539f24c8012a455b)

**Comment by harshad16** [comment]
Hindsight, the support for old pattern is not needed as graph-refersh would scheduled new solver, and graph-sycn would sync them based on new pattern. Also Sync-job is only run once that to necessary. 
So the above comment can be neglected.

**Comment by fridex** [comment]
Sounds like we can close this one. Feel free to reopen if required.

/close
